name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for rebase
          lfs: true  # Enable Git LFS if needed

      - name: Pull latest changes from Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://dpk1391981:$HF_TOKEN@huggingface.co/spaces/dpk1391981/aiagents || true
          git fetch hf main
          git pull --rebase hf main

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://dpk1391981:$HF_TOKEN@huggingface.co/spaces/dpk1391981/aiagents main
